### ISSUE TITLE
Build error while using esp_touch package

### ISSUE THREAD

**Issue by FarzBlues** [smaho-engineering/esptouch_flutter#1] opened 2019-12-28 05:30 UTC
I am facing build error when using smart config and esp_touch package in same flutter project.. How i can remove it??

 Error showing is  
     * What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

**Comment by vargavince91** [comment] 2020-03-09 15:03
I didn't use smartconfig and the esptouch_flutter package in the same project yet. Do you have an open-source Flutter app that I could `git checkout` and `flutter run`?

**Comment by vargavince91** [comment] 2020-03-09 16:02
We also fixed a couple of issues, could you please try using `esptouch_flutter: ^0.2.0`? Maybe your issues with the package were caused by those, seemingly unrelated issues that were fixed by version 0.2.x?

**Closed** 2020-07-17 12:35 UTC
