### ISSUE TITLE
Cannot pair new device on iOS 16

### ISSUE THREAD

**Issue by nguyen703** [smaho-engineering/esptouch_flutter#37] opened 2022-09-16 07:13 UTC
I tried to connect with different devices running iOS < 16 and it worked very well. But it could not match my iPhone XS Max and iPhone XS that have updated to iOS 16.

It would be great if you guys can release an update for iOS 16. Thank you a lot.

**Comment by max-koehler** [comment] 2022-09-16 07:25
@nguyen703 as mentioned in other issues, we are happy to help with contributions in PRs and otherwise. Currently, we can't say for sure when we will work on iOS16 compatibility.

**Comment by danilomna** [comment] 2022-09-28 17:07
@max-koehler this lib is awesome, your work is great.
Are there any chance you guys update to iOS16 compatibility? 
The situation became critical now that many users updated their iOS to 16.0.2
Nothing is working anymore.

**Comment by max-koehler** [comment] 2022-09-28 17:10
@danilomna we aren't working actively on iOS 16 compatibility. Would you be up to contribute a PR with the required changes?

**Comment by danilomna** [comment] 2022-09-28 17:18
@max-koehler yes, sure. How this could be done?

**Comment by danilomna** [comment] 2022-09-28 18:43
@max-koehler could I make a donation or sponsor to have this done? Are the any way?

**Comment by max-koehler** [comment] 2022-09-28 19:00
@danilomna what I meant was to upgrade the library to iOS16 yourself and contributing the changes in a pull request. We are happy to help wherever we can, but we can't commit resources to the upgrade ourselves at the moment. Therefore, a donation/sponsoring of any sort wouldn't help either.

**Comment by danilomna** [comment] 2022-09-28 19:08
@max-koehler oh, now I understood. I really wish I could contribute.  But I simply dont have enough knowledge and experience to do such thing, this is for pro devs like you guys. Best I can do would be pay for your time fixing this.

**Comment by max-koehler** [comment] 2022-09-28 19:46
@danilomna unfortunately I don't have an option to speed things up at the moment. 
Internally, we're slowly switching to a different Wi-Fi setup approach, which is why ESP Touch isn't our highest priority any more. Having said that, for backwards compatibility we might need to upgrade it in the foreseeable future, I just can't say for sure when. 

For what product do you use the library, if you don't mind me asking?

**Comment by danilomna** [comment] 2022-09-28 19:59
@max-koehler I understand your point. 
It is a pity, the lib was very usefull. 
Due to my lack of knowledge I have now idea where is the problem, but I wonder if maybe would be something simple to fix that could be catch by an expert dev eyes.

I use the lib in a flutter app project to config wifi devices. The app just do simple thinks like turn lamp on off, open gates.

**Comment by danilomna** [comment] 2022-09-29 19:19
@max-koehler 
@nguyen703 

seems the issue is not related to iOS 16 but just due to missing of multicast entitlement enable.

until iOS <16 I never had any issue so I never really enabled this. (I published many app versions with no issue).
just now after update iPhone to iOS 16.0.2 it stopped work.

So today I tried enable multicast entitlement,  followed the full procedure and double checked if all was updated.

Done, all working again, that is awesome.

Thanks for prompt reply, for time and patience.

ps. sorry bother you asking for lib update.

**Comment by nguyen703** [comment] 2022-09-29 19:41
<img width="520" alt="Screen Shot 2022-09-30 at 02 31 28" src="https://user-images.githubusercontent.com/89757787/193125984-9cd7a42f-d02c-44e7-8173-fb97470191a3.png">
 
@danilomna 
I did select the Multicast Networking but I couldn't find that option when Adding new capabilities. Could you please explain how you enabled the above entitlement?

Thank you a lot for the solution.

**Comment by danilomna** [comment] 2022-09-29 19:59
> <img alt="Screen Shot 2022-09-30 at 02 31 28" width="520" src="https://user-images.githubusercontent.com/89757787/193125984-9cd7a42f-d02c-44e7-8173-fb97470191a3.png">
> 
> @danilomna I did select the Multicast Networking but I couldn't find that option when Adding new capabilities. Could you please explain how you enabled the above entitlement?
> 
> Thank you a lot for the solution.


hi @nguyen703, 

In order to enable the multicast entitlement, do the following:

open you project in Xcode.
then open the .entitlement file.
add the highlighted line to file as shown in picture bellow:

![image](https://user-images.githubusercontent.com/57544850/193129650-8210d5e2-ff33-4116-a159-15ca9d201c04.png)

save file, close file.
build the project and run in on a real iPhone device (not emulator).
it is done

**Comment by ducnguyenenterprise** [comment] 2022-09-30 08:19
@danilomna Thank you so much for figuring it out. But we've discovered this issue since iOS 14.6 and have it documented [here](https://github.com/smaho-engineering/esptouch_flutter#breaking-change-in-ios-146). So I just want to make sure that your app still work without multicast enabled in ios 14.x, 15.x ?

**Comment by danilomna** [comment] 2022-09-30 08:43
> @danilomna Thank you so much for figuring it out. But we've discovered this issue since iOS 14.6 and have it documented [here](https://github.com/smaho-engineering/esptouch_flutter#breaking-change-in-ios-146). So I just want to make sure that your app still work without multicast enabled in ios 14.x, 15.x ?

@ducnguyenenterprise yes, my apps are still working without multicast enabled in iOS 15.x.
 I have two other iPhones for app testing, both with iOS 15.x and they still work fine for some reason.
The issue just show up when I updated the the iPhone to iOS16.0.2.

**Comment by ducnguyenenterprise** [comment] 2022-09-30 09:31
Interesting, thanks for that, we now know that the problem is not on the lib itself and don't need further investigation.
So @nguyen703 , you can close this issue after retesting your app with multicast enabled.

**Comment by nguyen703** [comment] 2022-09-30 09:37
@danilomna
@ducnguyenenterprise 

Hi, I really appreciate your contribution. Once I finish testing all my devices with the entitlement enabled, I will close this issue. Thanks a lot 😁

Have a nice day!

**Closed as completed** 2022-09-30 17:03 UTC
